services:
  android-build:
    build: .
    volumes:
      - ./enfr:/workspace
    command: sh -c "flutter pub get && flutter build apk --debug"

  web-build:
    build: .
    volumes:
      - ./enfr:/workspace
    command: sh -c "flutter pub get && flutter build web --base-href /enfr/"
